apiVersion: 1
datasources:
  - name: GCP Cloud Monitoring
    uid: P3BE906CE9E430760
    type: stackdriver
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      authenticationType: gce  # Uses GOOGLE_APPLICATION_CREDENTIALS
      defaultProject: "ethereal-effort-475219-c2"
      # Optional: set a location to scope queries
      # defaultLocation: "global"
      # Optional: set a default service (for Cloud Run/GAE)
      # defaultService: ""
      # Optional: custom namespaces for custom metrics
      # customMetricsNamespaces: []

