apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus-ds
    type: prometheus
    access: proxy
    url: http://host.docker.internal:9090
    isDefault: false
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: 15s
    version: 1

